from pathlib import Path
from rich.console import Console

console = Console()

PROJECT_AGENT_MD = """# b1CodingTool: Project Context
This is the project-specific `agents.md` context file.
It contains app logic, directory structures, and active tasks.

## Active Tasks
- Initial b1 setup

## Architecture Notes
- Follow the guidelines specified in the root `agents.md`.
"""

LOCAL_AGENT_MD = """# b1CodingTool: Local Context (personal, gitignored)
Personal, machine-specific notes and overrides. Not committed; compiled only into
your local agent files (CLAUDE.local.md, AGENTS.override.md, .agents/rules/local.md).

## Guardrails

## Edge cases
"""

def setup_context(root_dir: Path):
    def case_sensitive_exists(path: Path) -> bool:
        if not path.exists():
            return False
        return path.name in {p.name for p in path.parent.iterdir()}

    # Migrate lowercase root to uppercase if exists
    old_root_path = root_dir / "agents.md"
    root_agent_path = root_dir / "AGENTS.md"
    if case_sensitive_exists(old_root_path) and not case_sensitive_exists(root_agent_path):
        console.print("[yellow]Renaming existing agents.md to AGENTS.md...[/yellow]")
        temp_path = old_root_path.with_name(old_root_path.name + ".tmp_rename")
        old_root_path.rename(temp_path)
        temp_path.rename(root_agent_path)

    project_agent_dir = root_dir / ".agents" / "project"
    old_project_path = project_agent_dir / "agents.md"
    project_agent_path = project_agent_dir / "AGENTS.md"

    # Project-specific AGENTS.md: ensure dir exists and migrate lowercase to
    # uppercase before any content is written, so the root-migration block
    # below (which may read/write project_agent_path) sees the correct file.
    project_agent_dir.mkdir(parents=True, exist_ok=True)
    if case_sensitive_exists(old_project_path) and not case_sensitive_exists(project_agent_path):
        console.print("[yellow]Renaming existing project agents.md to AGENTS.md...[/yellow]")
        temp_path = old_project_path.with_name(old_project_path.name + ".tmp_rename")
        old_project_path.rename(temp_path)
        temp_path.rename(project_agent_path)

    # Root AGENTS.md is now a GENERATED OUTPUT. If a user authored one, migrate
    # its content into the shared project seed so nothing is lost, then leave the
    # root file for the translator to regenerate.
    if case_sensitive_exists(root_agent_path):
        root_content = root_agent_path.read_text(encoding="utf-8")
        is_generated = "AUTO-GENERATED BY b1CodingTool" in root_content
        if not is_generated and "b1CodingTool" not in root_content:
            existing_project = ""
            if case_sensitive_exists(project_agent_path):
                existing_project = project_agent_path.read_text(encoding="utf-8")
            merged = (existing_project.rstrip() + "\n\n" + root_content.strip() + "\n").lstrip()
            project_agent_path.write_text(merged, encoding="utf-8")
            console.print("[yellow]Migrated existing root AGENTS.md content into .agents/project/AGENTS.md.[/yellow]")

    if not case_sensitive_exists(project_agent_path):
        project_agent_path.write_text(PROJECT_AGENT_MD, encoding="utf-8")
        console.print("[green]Created project-specific AGENTS.md in .agents/project/.[/green]")
    else:
        console.print("[dim]Project-specific AGENTS.md already exists, skipping.[/dim]")

    # Personal local seed (gitignored)
    local_agent_dir = root_dir / ".agents" / "local"
    local_agent_dir.mkdir(parents=True, exist_ok=True)
    local_agent_path = local_agent_dir / "AGENTS.md"
    if not case_sensitive_exists(local_agent_path):
        local_agent_path.write_text(LOCAL_AGENT_MD, encoding="utf-8")
        console.print("[green]Created personal local seed in .agents/local/AGENTS.md.[/green]")
    else:
        console.print("[dim]Personal local seed already exists, skipping.[/dim]")
