import re
import shutil
from pathlib import Path
from rich.console import Console

console = Console()

class AgentTranslator:
    """
    Translates compiled context into agent-specific configuration files (CLAUDE.md, GEMINI.md, etc.)
    with tailored formatting for each provider, storing actual content in hidden directories.
    """
    
    SECTION_REGEX = re.compile(r"(<!-- b1CodingTool: (.*?) -->)", re.DOTALL)
    
    def __init__(self, project_dir: Path):
        self.project_dir = project_dir
        
    def generate_files(self, agents: list[str], compiled_content: str):
        """
        Generates tailored markdown files and directory structures for each target agent.
        """
        header = "<!-- THIS FILE IS AUTO-GENERATED BY b1CodingTool (b1 pair). DO NOT EDIT DIRECTLY. -->\n\n"
        sections = self._parse_sections(compiled_content)
        
        for agent in agents:
            agent_upper = agent.upper()
            agent_lower = agent.lower()
            
            # Setup hidden directory
            hidden_dir_name = f".{agent_lower}"
            hidden_dir_path = self.project_dir / hidden_dir_name
            context_dir_path = hidden_dir_path / "context"
            
            # Clean up old context dir if it exists
            if context_dir_path.is_dir():
                shutil.rmtree(context_dir_path)
            elif context_dir_path.exists():
                context_dir_path.unlink()
            
            context_dir_path.mkdir(parents=True, exist_ok=True)
            
            filemap_links = []
            
            # Write individual section files
            for name, body in sections:
                relative_dir, file_name = self._get_file_info(name)
                
                # Make sure the target directory exists
                target_dir = context_dir_path / relative_dir
                target_dir.mkdir(parents=True, exist_ok=True)
                
                file_path = target_dir / file_name
                
                formatted_body = self._format_section(agent_upper, name, body)
                file_path.write_text(formatted_body, encoding="utf-8")
                
                # Add to filemap list
                # Build the relative path string ensuring forward slashes
                rel_path = f"{hidden_dir_name}/context/{relative_dir}/{file_name}" if relative_dir else f"{hidden_dir_name}/context/{file_name}"
                filemap_links.append(f"- [{name}]({rel_path})")
            
            # Generate the root filemap
            root_filename = f"{agent_upper}.md"
            out_path = self.project_dir / root_filename
            
            instructions = (
                f"# {root_filename.replace('.md', '')} Context Filemap\n\n"
                "To prevent context bloat, the full project and module contexts are not inlined here. "
                "Instead, they are available in the files linked below. "
                "**Please read these files when you need specific context.**\n\n"
            )
            
            final_root_content = header + instructions + "\n".join(filemap_links) + "\n"
                
            out_path.write_text(final_root_content, encoding="utf-8")
            
            console.print(f"[green]✔ Generated:[/green] {root_filename} and {hidden_dir_name}/context/")

        # Ensure .gitignore has these entries
        self._update_gitignore(agents)

    def _update_gitignore(self, agents: list[str]):
        """Ensures generated files and hidden directories are in .gitignore"""
        gitignore_path = self.project_dir / ".gitignore"
        existing_lines = []
        if gitignore_path.exists():
            existing_lines = gitignore_path.read_text(encoding="utf-8").splitlines()
            
        entries_to_add = []
        for agent in agents:
            root_file = f"{agent.upper()}.md"
            hidden_dir = f".{agent.lower()}/"
            
            if root_file not in existing_lines:
                entries_to_add.append(root_file)
            if hidden_dir not in existing_lines:
                entries_to_add.append(hidden_dir)
                
        if entries_to_add:
            mode = "a" if gitignore_path.exists() else "w"
            with open(gitignore_path, mode, encoding="utf-8") as f:
                if existing_lines and existing_lines[-1].strip() != "":
                    f.write("\n")
                if not existing_lines or "# b1CodingTool Generated" not in existing_lines:
                    f.write("# b1CodingTool Generated\n")
                for entry in entries_to_add:
                    f.write(f"{entry}\n")

    def _get_file_info(self, name: str) -> tuple[str, str]:
        """
        Determines the subdirectory and filename based on the section name.
        Example: 'Module Context [fastapi] - SKILL.md' -> ('fastapi', 'SKILL.md')
                 'Root Context' -> ('', 'root_context.md')
        """
        # Match 'Module Context [module_name] - filename'
        module_context_match = re.match(r"Module Context \[(.*?)\] - (.*)", name)
        if module_context_match:
            return module_context_match.group(1).strip(), module_context_match.group(2).strip()
            
        # Match 'Module Capabilities [module_name]'
        module_cap_match = re.match(r"Module Capabilities \[(.*?)\]", name)
        if module_cap_match:
            return module_cap_match.group(1).strip(), "capabilities.md"
            
        # Default fallback (e.g. Root Context, Project Context)
        return "", f"{self._safe_filename(name)}.md"

    def _safe_filename(self, name: str) -> str:
        """Converts section name to safe filename (e.g. 'Root Context' -> 'root_context')"""
        safe = name.lower().replace(" ", "_").replace("[", "").replace("]", "").replace("-", "_").replace(".", "_")
        return re.sub(r"[^a-z0-9_]", "", safe)

    def _parse_sections(self, content: str):
        """Splits the compiled content into a list of (section_name, section_content) tuples."""
        sections = []
        matches = list(self.SECTION_REGEX.finditer(content))
        
        if not matches:
            return [("Context", content.strip())]
            
        for i, match in enumerate(matches):
            section_name = match.group(2).strip()
            start_pos = match.end()
            end_pos = matches[i+1].start() if i + 1 < len(matches) else len(content)
            section_content = content[start_pos:end_pos].strip()
            sections.append((section_name, section_content))
            
        return sections

    def _format_section(self, agent: str, name: str, body: str) -> str:
        """Formats a single section based on the target agent."""
        if agent == "CLAUDE":
            if "[dart]" in name.lower():
                tag_name = "dart_context"
            else:
                tag_name = self._safe_filename(name)
            return f"<{tag_name}>\n{body}\n</{tag_name}>"
            
        elif agent == "GEMINI":
            preamble = (
                "You are a Gemini CLI agent specializing in software engineering tasks. "
                "Follow the project conventions and architectural patterns defined below strictly."
            )
            return f"> [!IMPORTANT]\n> {preamble}\n\n## {name}\n{body}"
            
        else:
            return body
