import shutil
from pathlib import Path
from rich.console import Console

from b1.core.compiled import CompiledContext, ContextItem, SHARED, PERSONAL, PROPRIETARY
from b1.core.shims import write_agent_shims

console = Console()

HEADER = "<!-- AUTO-GENERATED BY b1CodingTool (b1 pair). DO NOT EDIT DIRECTLY. -->\n\n"


class AgentTranslator:
    def __init__(self, project_dir: Path):
        self.project_dir = project_dir

    def generate_files(self, agents: list[str], compiled: CompiledContext):
        # Root AGENTS.md is the universal native file — always rendered.
        self.render_root_agents(compiled)

        upper = {a.upper() for a in agents}
        if "CLAUDE" in upper:
            self.render_claude(compiled)
        if "CODEX" in upper:
            self.render_codex(compiled)
        if "ANTIGRAVITY" in upper:
            self.render_antigravity(compiled)

        write_agent_shims(self.project_dir)
        self._ensure_gitignore()

    # ---- helpers ----

    def _get_agent_guide(self, filename: str) -> str:
        return f"""# {filename}

## 🤖 B1CodingTool Workspace Map & Agent Guide
> [!IMPORTANT]
> **This file is auto-generated by `b1 pair`. Do not edit it directly.**
>
> - **To update project-wide rules/context**: Edit [.agents/project/AGENTS.md](.agents/project/AGENTS.md)
> - **To update personal local rules**: Edit [.agents/local/AGENTS.md](.agents/local/AGENTS.md)
> - **To regenerate files**: Run `b1 pair` (or `uv run b1 pair`) to sync changes.

---
"""

    def _pointer_line(self, item: ContextItem) -> str:
        return f"- [{item.title}]({item.source_path})"

    def _inline_block(self, item: ContextItem) -> str:
        return f"## {item.title}\n\n{item.body}\n"

    # ---- shared / root ----

    def render_root_agents(self, compiled: CompiledContext):
        parts = [HEADER, self._get_agent_guide("AGENTS.md")]
        eager = compiled.filter(visibility=SHARED, eager=True)
        for item in eager:
            parts.append("\n" + self._inline_block(item))
        lazy = compiled.filter(visibility=SHARED, eager=False)
        if lazy:
            parts.append("\n## Reference (read on demand)\n\n")
            parts.extend(self._pointer_line(i) + "\n" for i in lazy)
        (self.project_dir / "AGENTS.md").write_text("".join(parts), encoding="utf-8")
        console.print("[green]✔ Generated:[/green] AGENTS.md")

    # ---- Claude ----

    def render_claude(self, compiled: CompiledContext):
        context_dir = self.project_dir / ".claude" / "context"
        if context_dir.exists():
            shutil.rmtree(context_dir)
        context_dir.mkdir(parents=True, exist_ok=True)

        parts = [HEADER, self._get_agent_guide("CLAUDE.md")]
        for item in compiled.filter(visibility=SHARED, eager=True):
            parts.append("\n" + self._inline_block(item))

        # Eager proprietary items are safe to inline here too: CLAUDE.md is
        # gitignored, so this never reaches committed/shared files (unlike
        # AGENTS.md, which must exclude proprietary content).
        for item in compiled.filter(visibility=PROPRIETARY, eager=True):
            parts.append("\n" + self._inline_block(item))

        # All lazy items (public + proprietary) -> copies in gitignored .claude/context,
        # linked as a filemap. .claude/ is gitignored so proprietary content is safe here.
        lazy = [i for i in compiled.items if not i.eager and i.visibility in (SHARED, PROPRIETARY)]
        if lazy:
            parts.append("\n## Reference (read on demand)\n\n")
            for idx, item in enumerate(lazy):
                fname = f"{idx:03d}_{Path(item.source_path).name}"
                (context_dir / fname).write_text(item.body, encoding="utf-8")
                parts.append(f"- [{item.title}](.claude/context/{fname})\n")

        (self.project_dir / "CLAUDE.md").write_text("".join(parts), encoding="utf-8")

        personal = compiled.filter(visibility=PERSONAL, eager=True)
        local_parts = [HEADER, "# CLAUDE.local.md (personal)\n"]
        for item in personal:
            local_parts.append("\n" + self._inline_block(item))
        (self.project_dir / "CLAUDE.local.md").write_text("".join(local_parts), encoding="utf-8")
        console.print("[green]✔ Generated:[/green] CLAUDE.md, CLAUDE.local.md, .claude/context/")

    # ---- Codex / Antigravity (personal + proprietary vehicles) ----

    def _render_personal_vehicle(self, compiled: CompiledContext, out_path: Path, title: str):
        personal = compiled.filter(visibility=PERSONAL, eager=True)
        proprietary_lazy = compiled.filter(visibility=PROPRIETARY, eager=False)
        proprietary_eager = compiled.filter(visibility=PROPRIETARY, eager=True)
        if not personal and not proprietary_lazy and not proprietary_eager:
            if out_path.exists():
                out_path.unlink()
            return
        parts = [HEADER, f"# {title}\n"]
        for item in personal:
            parts.append("\n" + self._inline_block(item))
        for item in proprietary_eager:
            parts.append("\n" + self._inline_block(item))
        if proprietary_lazy:
            parts.append("\n## Proprietary reference (read on demand)\n\n")
            parts.extend(self._pointer_line(i) + "\n" for i in proprietary_lazy)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text("".join(parts), encoding="utf-8")
        console.print(f"[green]✔ Generated:[/green] {out_path.relative_to(self.project_dir)}")

    def render_codex(self, compiled: CompiledContext):
        self._render_personal_vehicle(
            compiled, self.project_dir / "AGENTS.override.md", "AGENTS.override.md (personal)")

    def render_antigravity(self, compiled: CompiledContext):
        self._render_personal_vehicle(
            compiled, self.project_dir / ".agents" / "rules" / "local.md", "Local rules (personal)")

    def _ensure_gitignore(self):
        gitignore = self.project_dir / ".gitignore"
        entries = ["CLAUDE.md", "CLAUDE.local.md", "AGENTS.override.md",
                   ".claude/", ".agents/local/", ".agents/rules/local.md",
                   ".agents/skills/b1-rule.md", ".agents/skills/b1-edge-case.md",
                   ".agents/skills/b1-reconcile.md", ".agents/.b1-snapshots/"]
        existing = gitignore.read_text(encoding="utf-8").splitlines() if gitignore.exists() else []
        missing = [e for e in entries if e not in existing]
        if missing:
            with open(gitignore, "a", encoding="utf-8") as f:
                if existing and existing[-1].strip():
                    f.write("\n")
                if "# b1CodingTool generated agent files" not in existing:
                    f.write("# b1CodingTool generated agent files\n")
                for e in missing:
                    f.write(e + "\n")
