# tests/unit/test_compiler.py
from pathlib import Path
from b1.core.compiler import ContextCompiler


def _scaffold(root: Path, root_md=None, project_md=None, modules=None):
    """Helper: builds a minimal project layout in root."""
    (root / ".agents" / "project").mkdir(parents=True)
    (root / ".agents" / "modules").mkdir(parents=True)
    if root_md is not None:
        (root / "AGENTS.md").write_text(root_md, encoding="utf-8")
    if project_md is not None:
        (root / ".agents" / "project" / "AGENTS.md").write_text(project_md, encoding="utf-8")
    if modules:
        for name, context_files in modules.items():
            mod_ctx = root / ".agents" / "modules" / name / "context"
            mod_ctx.mkdir(parents=True)
            for fname, content in context_files.items():
                (mod_ctx / fname).write_text(content, encoding="utf-8")


def test_compile_returns_empty_string_when_no_files(tmp_path):
    (tmp_path / ".agents" / "modules").mkdir(parents=True)
    compiler = ContextCompiler(tmp_path)
    assert compiler.compile() == ""


def test_compile_includes_root_agent_md(tmp_path):
    _scaffold(tmp_path, root_md="# Root context\n")
    result = ContextCompiler(tmp_path).compile()
    assert "Root context" in result


def test_compile_includes_project_agent_md(tmp_path):
    _scaffold(tmp_path, project_md="# Project context\n")
    result = ContextCompiler(tmp_path).compile()
    assert "Project context" in result


def test_compile_includes_module_context_files(tmp_path):
    _scaffold(tmp_path, modules={"django": {"best-practices.md": "# Django tips\n"}})
    result = ContextCompiler(tmp_path).compile()
    assert "Django tips" in result


def test_compile_includes_all_modules(tmp_path):
    _scaffold(tmp_path, modules={
        "django": {"conventions.md": "Django conventions"},
        "fastapi": {"best-practices.md": "FastAPI tips"},
    })
    result = ContextCompiler(tmp_path).compile()
    assert "Django conventions" in result
    assert "FastAPI tips" in result


def test_compile_includes_html_comment_headers(tmp_path):
    _scaffold(tmp_path, root_md="# Root\n", modules={"django": {"best-practices.md": "# tips"}})
    result = ContextCompiler(tmp_path).compile()
    assert "<!-- b1CodingTool:" in result


def test_compile_handles_missing_modules_dir_gracefully(tmp_path):
    (tmp_path / ".agents" / "project").mkdir(parents=True)
    (tmp_path / "AGENTS.md").write_text("# Root\n", encoding="utf-8")
    # no modules dir at all
    result = ContextCompiler(tmp_path).compile()
    assert "Root" in result


def test_compile_strips_generated_section(tmp_path):
    (tmp_path / ".agents" / "project").mkdir(parents=True)
    root_md = (
        "# Root Context\n"
        "Some manual content.\n\n"
        "<!-- b1CodingTool: start -->\n"
        "<!-- THE FOLLOWING SECTION IS AUTO-GENERATED BY b1CodingTool. DO NOT EDIT DIRECTLY. -->\n"
        "# AGENTS Context Filemap\n"
        "- [Root Context](.claude/context/root_context.md)\n"
        "<!-- b1CodingTool: end -->"
    )
    (tmp_path / "AGENTS.md").write_text(root_md, encoding="utf-8")
    result = ContextCompiler(tmp_path).compile()
    assert "Root Context" in result
    assert "Some manual content." in result
    assert "AGENTS Context Filemap" not in result
    assert "b1CodingTool: start" not in result



def test_compile_includes_github_metadata(tmp_path):
    from b1.core.config import B1Config
    from b1.core.compiler import ContextCompiler
    config = B1Config(
        github_owner="brandon",
        github_repo="b1CodingTool",
        default_branch="main"
    )
    result = ContextCompiler(tmp_path, config=config).compile()
    assert "<!-- b1CodingTool: GitHub Repository -->" in result
    assert "https://github.com/brandon/b1CodingTool" in result
    assert "Default Branch: main" in result


def test_compile_includes_module_capabilities(tmp_path):
    import yaml
    mod_dir = tmp_path / ".agents" / "modules" / "flutter"
    mod_dir.mkdir(parents=True)
    
    config = {
        "name": "flutter",
        "version": "1.0.0",
        "type": "development",
        "skills": [{"name": "Skill 1", "description": "Desc 1"}],
        "commands": [{"name": "/cmd1", "description": "Cmd 1 desc"}]
    }
    (mod_dir / "b1-module.yaml").write_text(yaml.dump(config))
    
    result = ContextCompiler(tmp_path).compile()
    assert "### flutter Capabilities" in result
    assert "#### Commands" in result
    assert "- `/cmd1`: Cmd 1 desc" in result
    assert "#### Skills" in result
    assert "- **Skill 1**: Desc 1" in result
